#######
# Compiled from data/explosion-laser/functions/load.mcscript
# to .//data/explosion-laser/functions/mcscript/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######

# Extended from data/explosion-laser/functions/main.mcscript
# to data/explosion-laser/functions/mcscript/load.mcfunction
# please do not touch this file!
# it is used by the compiler!
scoreboard objectives add mcscript_raycast dummy
