#######
# Compiled from data/explosion-laser/functions/main.mcscript
# to data/explosion-laser/functions/mcscript/raycast2.mcfunction
#
# Generated by Minecraft Script for 1.13
######
particle dragon_breath ^ ^ ^2 0.01 0.01 0.01 0.001 10 force
scoreboard players add raycast2 mcscript_raycast 1
execute positioned ^ ^ ^1 unless block ~ ~ ~ air run tag @s add mcscriptStop
execute positioned ^ ^ ^1 if entity @s[tag=!mcscriptStop] if block ~ ~ ~ air if score raycast2 mcscript_raycast matches ..100 run function explosion-laser:mcscript/raycast2
execute if score raycast2 mcscript_raycast matches ..100 if entity @s[tag=mcscriptStop] positioned ^ ^ ^1 run summon falling_block ~ ~ ~ {BlockState:{Name:"minecraft:bedrock"},Time:1}
execute if score raycast2 mcscript_raycast matches ..100 if entity @s[tag=mcscriptStop] positioned ^ ^ ^1 run particle campfire_cosy_smoke ~ ~ ~ 0.1 0.1 0.1 1 20 force
execute if score raycast2 mcscript_raycast matches ..100 if entity @s[tag=mcscriptStop] positioned ^ ^ ^1 run summon creeper ~ ~-1 ~ {Silent:1,Fuse:0,ExplosionRadius:10, ActiveEffects:[{id:invisibility,Amplifier:1,Duration:10,ShowParticles:0}]}
tag @s[tag=mcscriptStop] remove mcscriptStop
