#######
# Compiled from data/explosion-laser/functions/load.mcscript
# to .//data/explosion-laser/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function explosion-laser:mcscript/load

tellraw @a "§a[Explosion Laser]§f Datapack loaded!"