#######
# Compiled from data/explosion-laser/functions/main.mcscript
# to .//data/explosion-laser/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[nbt={SelectedItem:{id:"minecraft:stick",tag:{display:{Name:'{"text":"Explosion Laser"}'}}}}] at @s run clear @s minecraft:stick{display:{Name:'{"text":"Explosion Laser"}'}} 1
execute as @a[nbt={SelectedItem:{id:"minecraft:stick",tag:{display:{Name:'{"text":"Explosion Laser"}'}}}}] at @s run give @s stick{display:{Name:'{"text":"§b§lExplosion Laser"}'},Enchantments:[{id:infinity,lvl:1}]} 1
execute as @a[nbt={SelectedItem:{id:"minecraft:stick",tag:{display:{Name:'{"text":"§b§lExplosion Laser"}'}}}}] at @s run particle minecraft:bubble ^1 ^1.5 ^2 0.01 0.01 0.01 0.00001 1 force
execute as @a[nbt={SelectedItem:{id:"minecraft:stick",tag:{display:{Name:'{"text":"§b§lExplosion Laser"}'}}}}] at @s run particle minecraft:bubble ^-1 ^1.5 ^2 0.01 0.01 0.01 0.00001 1 force
execute as @a[nbt={SelectedItem:{id:"minecraft:stick",tag:{display:{Name:'{"text":"§b§lExplosion Laser"}'}}}}] at @s run particle minecraft:bubble ^ ^2.5 ^2 0.01 0.01 0.01 0.00001 1 force
execute as @a[nbt={SelectedItem:{id:"minecraft:stick",tag:{display:{Name:'{"text":"§b§lExplosion Laser"}'}}}}] at @s run particle minecraft:bubble ^ ^0.5 ^2 0.01 0.01 0.01 0.00001 1 force
execute as @a[nbt={SelectedItem:{id:"minecraft:stick",tag:{display:{Name:'{"text":"§b§lExplosion Laser"}'}}}}] at @s run scoreboard players set raycast1 mcscript_raycast 0
execute as @a[nbt={SelectedItem:{id:"minecraft:stick",tag:{display:{Name:'{"text":"§b§lExplosion Laser"}'}}}}] at @s positioned ~ ~1 ~ run function explosion-laser:mcscript/raycast1